package com.elearning.server.repository;

import java.util.List;

import com.elearning.server.model.Enrollment;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Repository
public interface EnrollmentRepository extends JpaRepository<Enrollment, String>, JpaSpecificationExecutor<Enrollment> {
    @Query(
        value = "SELECT * FROM enrollment k where k.id_class = :id_class and k.disetujui = :disetujui", 
        nativeQuery=true
    )
    public Page<Enrollment> findByKelas(@Param("id_class") String idKelas,@Param("disetujui") Boolean disetujui,Pageable paging);

    @Query(
        value = "SELECT * FROM enrollment k where k.id_mahasiswa = :id_mahasiswa and k.disetujui = :disetujui", 
        nativeQuery=true
    )
    public Page<Enrollment> findByMahasiswa(@Param("id_mahasiswa") String idMahasiswa,@Param("disetujui") Boolean disetujui,Pageable paging);
    @Query(
        value = "select case when count(k)> 0 then true else false end from com.elearning.server.model.Enrollment k where k.mahasiswa.nim = :id_mahasiswa and k.kelas.id = :id_class"
    )
    public boolean existsByMahasiswaKelas(@Param("id_mahasiswa") String idMahasiswa,@Param("id_class") String idKelas);
    @Query(
        value = "SELECT * FROM enrollment k where k.id_mahasiswa = :id_mahasiswa and k.id_class = :id_class", 
        nativeQuery=true
    )
    public List<Enrollment> findByMahasiswaKelas(@Param("id_mahasiswa") String idMahasiswa,@Param("id_class") String idKelas);
}

