package com.elearning.server.repository;

import java.util.List;

import com.elearning.server.model.Hasil;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Repository
public interface HasilRepository extends JpaRepository<Hasil, String>, JpaSpecificationExecutor<Hasil> {
    @Query(
        value = "SELECT * FROM hasil k where k.id_soal = :id_soal and k.status = :status", 
        nativeQuery=true
    )
    public Page<Hasil> findBySoal(@Param("id_soal") String idSoal,@Param("status") String status,Pageable paging);

    @Query(
        value = "SELECT * FROM hasil k where k.id_mahasiswa = :id_mahasiswa", 
        nativeQuery=true
    )
    public Page<Hasil> findByMahasiswa(@Param("id_mahasiswa") String idMahasiswa,Pageable paging);
    @Query(
        value = "select case when count(k)> 0 then true else false end from com.elearning.server.model.Hasil k where k.mahasiswa.nim = :id_mahasiswa and k.soal.id = :id_soal"
    )
    public boolean existsByMahasiswaSoal(@Param("id_mahasiswa") String idMahasiswa,@Param("id_soal") String idSoal);
    @Query(
        value = "SELECT * FROM enrollment k where k.id_mahasiswa = :id_mahasiswa and k.id_soal = :id_soal", 
        nativeQuery=true
    )
    public List<Hasil> findByMahasiswaSoal(@Param("id_mahasiswa") String idMahasiswa,@Param("id_soal") String idSoal);
}
