
package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Dosen;
import com.elearning.server.model.User;
import com.elearning.server.repository.DosenRepository;
import com.elearning.server.repository.UserRepository;
import com.elearning.server.service.manager.DosenManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class CurrentUserService{

	private UserRepository userRepository;

	@Autowired
	public CurrentUserService(UserRepository userRepository) {
		this.userRepository = userRepository;
	}


	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
public User pilihUser(String email) {
    // TODO Auto-generated method stub
    return userRepository.findByEmail(email);
}

}

