package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Dosen;
import com.elearning.server.repository.DosenRepository;
import com.elearning.server.service.manager.DosenManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class DosenService implements DosenManager{

	private DosenRepository dosenRepository;

	@Autowired
	public DosenService(DosenRepository dosenRepository) {
		this.dosenRepository = dosenRepository;
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<Dosen> semuaDosen() {
		return dosenRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Dosen simpanDosen(Dosen ds) {
		return dosenRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Dosen pilihDosen(String id) {
		// TODO Auto-generated method stub
		return dosenRepository.getOne(id);
	}

}
