package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Enrollment;
import com.elearning.server.repository.EnrollmentRepository;
import com.elearning.server.service.manager.EnrollmentManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class EnrollmentService implements EnrollmentManager{

	private EnrollmentRepository enrollmentRepository;

	@Autowired
	public EnrollmentService(EnrollmentRepository enrollmentRepository) {
		this.enrollmentRepository = enrollmentRepository;
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<Enrollment> semuaEnrollment() {
		return enrollmentRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Enrollment simpanEnrollment(Enrollment ds) {
		return enrollmentRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Enrollment pilihEnrollment(String id) {
		// TODO Auto-generated method stub
		return enrollmentRepository.getOne(id);
	}
}
