package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Hasil;
import com.elearning.server.repository.HasilRepository;
import com.elearning.server.repository.SoalRepository;
import com.elearning.server.service.manager.HasilManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class HasilService implements HasilManager{

	private HasilRepository hasilRepository;
	private SoalRepository soalRepository;

	@Autowired
	public HasilService(HasilRepository hasilRepository, SoalRepository soalRepository) {
		this.hasilRepository = hasilRepository;
		this.soalRepository = soalRepository;
	}


	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<Hasil> semuaHasil() {
		return hasilRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Hasil simpanHasil(Hasil ds) {
		return hasilRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Hasil pilihHasil(String id) {
		// TODO Auto-generated method stub
		return hasilRepository.getOne(id);
	}
}
