package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Jurusan;
import com.elearning.server.repository.JurusanRepository;
import com.elearning.server.service.manager.JurusanManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class JurusanService implements JurusanManager {

	private JurusanRepository jurusanRepository;

	@Autowired
	public JurusanService(JurusanRepository jurusanRepository) {
		this.jurusanRepository = jurusanRepository;
	}


	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<Jurusan> semuaJurusan() {
		return jurusanRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Jurusan simpanJurusan(Jurusan ds) {
		return jurusanRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Jurusan pilihJurusan(String id) {
		// TODO Auto-generated method stub
		return jurusanRepository.findById(id).get();
	}

	public void hapusJurusan(String id){
		jurusanRepository.deleteById(id);
	}
}

