package com.elearning.server.service;

import java.util.List;
import java.util.Optional;

import com.elearning.server.model.MataKuliah;
import com.elearning.server.repository.MataKuliahRepository;
import com.elearning.server.service.manager.MataKuliahManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import lombok.extern.slf4j.Slf4j;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Slf4j
@Service
public class MataKuliahService implements MataKuliahManager{

	private MataKuliahRepository mataKuliahRepository;

	@Autowired
	public MataKuliahService(MataKuliahRepository mataKuliahRepository) {
		this.mataKuliahRepository = mataKuliahRepository;
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<MataKuliah> semuaMataKuliah(){
		return mataKuliahRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public MataKuliah simpanMataKuliah(MataKuliah ds) {
		return mataKuliahRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public MataKuliah pilihMataKuliah(String id) {
		// TODO Auto-generated method stub
		
		return mataKuliahRepository.findById(id).get();
	}

	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void hapusMataKuliah(String id) {
		// TODO Auto-generated method stub
		mataKuliahRepository.deleteById(id);
	}

}
