package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Materi;
import com.elearning.server.repository.MateriRepository;
import com.elearning.server.service.manager.MateriManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class MateriService implements MateriManager{

	private MateriRepository materiRepository;

	@Autowired
	public MateriService(MateriRepository materiRepository) {
		this.materiRepository = materiRepository;
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public List<Materi> semuaMateri() {
		return materiRepository.findAll();
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Materi simpanMateri(Materi ds) {
		return materiRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Materi pilihMateri(String id) {
		// TODO Auto-generated method stub
		return materiRepository.getOne(id);
	}

}
