package com.elearning.server.service;

import java.util.List;

import com.elearning.server.model.Materi;
import com.elearning.server.model.Soal;
import com.elearning.server.repository.SoalRepository;
import com.elearning.server.service.manager.SoalManager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Spring Data Generator on 11/09/2019
*/
@Service
public class SoalService implements SoalManager{

	private SoalRepository soalRepository;

	@Autowired
	public SoalService(SoalRepository soalRepository) {
		this.soalRepository = soalRepository;
	}

	@Transactional(propagation = Propagation.REQUIRED, readOnly = true)
	@Override
	public Page<Soal> semuaSoal(Pageable paging) {
		return soalRepository.findAll(paging);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Soal simpanSoal(Soal ds) {
		return soalRepository.save(ds);
	}

	@Transactional(propagation = Propagation.REQUIRED)
	@Override
	public Soal pilihSoal(String id) {
		// TODO Auto-generated method stub
		return soalRepository.findById(id).get();
	}

	
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void hapusSoal(String id) {
		// TODO Auto-generated method stub
		soalRepository.deleteById(id);
	}

	
}
